[versions]
accompanist = "0.34.0"
activity-compose = "1.10.0"
appcompat = "1.7.0"
arrow-core = "1.0.1"
buildkonfig = "0.15.1"
better-parse = "0.4.4"
camera = "1.4.1"
coil-compose = "2.5.0"
compose = "1.7.3"
crashlytics = "3.0.3"
datastore-preferences = "1.1.2"
datetime-dialog = "0.5.1"
debounce = "1.2.0"
desugar-jdk-libs = "2.1.4"
firebase-dynamic-links-ktx = "22.1.0"
gitlive-firebase = "2.1.0"
google-services = "4.4.2"
junit-jupiter-engine = "5.8.2"
kodein = "7.11.0"
coroutines = "1.8.0"
korau = "2.2.0"
kotlinx-collections-immutable = "0.3.5"
kotlinx-serialization-json = "1.6.3"
ktor = "2.3.12"
mockk = "1.13.7"
moko-resources = "0.24.0-beta-1"
moko-parcelize = "0.9.0"
kotlin = "2.1.0"
ktlint-gradle = "12.1.1"
android-gradle = "8.8.2"
napier = "2.1.0"
pdfbox = "2.0.27"
pdfbox-android = "2.0.27.0"
play-services-auth = "21.2.0"
reactivenetwork-rx2 = "3.0.8"
richtext = "1.0.0-alpha01"
semver = "2.0.0"
uuid = "0.3.1"
voyager = "1.0.0"
#noinspection GradleDependency - Intentionally keeping this version as it is the last version that supports SDK < 24
zxing = "3.3.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow-core" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
better-parse = { module = "com.github.h0tk3y.betterParse:better-parse", version.ref = "better-parse" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
datetime-dialog = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "datetime-dialog" }
debounce = { module = "io.github.mmolosay:debounce", version.ref = "debounce" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive-firebase" }
firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "gitlive-firebase" }
firebase-dynamic-links-ktx = { module = "com.google.firebase:firebase-dynamic-links-ktx", version.ref = "firebase-dynamic-links-ktx" }
firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "gitlive-firebase" }
firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive-firebase" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "gitlive-firebase" }
firebase-functions = { module = "dev.gitlive:firebase-functions", version.ref = "gitlive-firebase" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-di-framework-android-core = { module = "org.kodein.di:kodein-di-framework-android-core", version.ref = "kodein" }
kodein-di-framework-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
korau = { module = "com.soywiz.korlibs.korau:korau", version.ref = "korau" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-parcelize = { module = "dev.icerock.moko:parcelize", version.ref = "moko-parcelize" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfbox-android" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
reactivenetwork-rx2 = { module = "com.github.pwittchen:reactivenetwork-rx2", version.ref = "reactivenetwork-rx2" }
resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "richtext" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
richtext-ui-material = { module = "com.halilibo.compose-richtext:richtext-ui-material", version.ref = "richtext" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }